### ISSUE TITLE
Contact information and sourcecode?

### ISSUE THREAD

**Issue by brylie** [DigitalDentalExchange/DigitalDentalExchange#1]
We found a few [Meteor.js packages on Atmosphere](https://atmospherejs.com/ddxdental), but could not locate the source code. Where can we find the source code for the OpenID Connect related packages? How can we contact the developers?

**Comment by ddxdental** [comment]
Packages are in a sample app here:

https://github.com/DigitalDentalExchange/ddx-log/tree/master/packages

I guess we should pull the packages out and put them in there own repo
